<?php


header('Content-Type: application/json');
session_start();
function isValidRequest()
{
    $request_method = $_SERVER['REQUEST_METHOD'];
    $expected_request_method = 'POST';
    if ($request_method != $expected_request_method) {
        return false;

    }


    exit("Request failed");

}





require_once '../security/config.php';
require_once '../security/database.php'; // Required for Necessary Database Connections.
require '../phpmailer/PHPMailerAutoload.php';



class Login extends DatabaseConnection {


    private $username , $password  , $login_type , $data , $user_id , $remember_me , $failed_login_error = "login details not found" , $successful_login = "login successful!" , $error;
    function __construct()
    {
        parent::__construct();
    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    public function  isReady() : bool {

        $data = ($_POST["data"]) ?? null;
        if ($data != null) {

            $data = json_decode($data , true);
            $this->data = $data;
            return true;

        }

        return false;
    }
    public  function setDetails () : bool {

       $this->username = strtolower($this->data["username"]);
       $this->password = $this->data["password"];
       $this->login_type = $this->data["loginType"];
       $this->remember_me = $this->data["rememberMe"];

      return true;

    }


    private function  isValidLogin() : bool {
        $users_table_name = $this->users_table_name;
        $username = strtolower($this->username);
        $password = md5($this->password);
        $login_type = ($this->login_type == "email") ? "email_address" : "username";
        $sql = "SELECT {$login_type} FROM {$users_table_name} WHERE {$login_type} = '{$username}' AND password = '{$password}'";
        $result = $this->conn->prepare($sql);
        $result->execute();
        $num_rows = $result->rowCount();

        if($num_rows > 0) {
            return true;
        }


        return false;

    }
    public function get_user_profile(): array
    {
        $users_table_name = $this->users_table_name;
        $username = strtolower($this->username);
        $sql = "SELECT * FROM {$users_table_name} WHERE username = '{$username}'";
        $result = $this->conn->prepare($sql);
        $result->execute();
        $set_type_record = $result->setFetchMode(PDO::FETCH_ASSOC);
        $record = $result->fetchAll();
        return $record;
    }


    public  function  Processor() {

        if($this->isReady()){

            $this->setDetails();

            if($this->isValidLogin()){
                $time = time();

                $thirty_days_from_now = (86400 * 30) + $time;
                $this->user_id = $this->get_user_profile()[0]["user_id"];

                if ($this->remember_me != 1) {


                    setcookie("current_active_user" , "Deleted" , time() - 300 , "/");


                }

                else {
                    setcookie("current_active_user" , $this->user_id , $thirty_days_from_now , "/");

                }


                $this->error = Array("success" => 1 , "error" => $this->successful_login);
                $this->error = json_encode($this->error);
                $_SESSION["current_active_user"] = strtolower($this->user_id);
                return $this->error;










            }

            else {
                     $this->error = Array("success" => 0 , "error" => $this->failed_login_error);
                     $this->error = json_encode($this->error);
                     return $this->error;


            }
        }
    }



}

$login = new Login();
echo $login->Processor();
?>