<?php


header('Content-type:application/json;charset=utf-8');
ob_start();
session_start();
function isValidRequest()
{
    $request_method = $_SERVER['REQUEST_METHOD'];
    $expected_request_method = 'POST';
    if ($request_method != $expected_request_method) {
        return false;

    }


    exit("Request failed");

}





require_once '../security/config.php';
require_once '../security/database.php'; // Required for Necessary Database Connections.
require '../phpmailer/PHPMailerAutoload.php';



class Login extends DatabaseConnection {


    private $username , $phone, $data , $user_id  , $failed_login_error = "login details not found" , $successful_login = "Login successful!" , $error;
    function __construct()
    {
        parent::__construct();
    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    private final function  isReady() : bool {

        $data = ($_POST["data"]) ?? null;
        if ($data != null) {

            $data = json_decode($data , true);
            $this->data = $data;

            return true;

        }

        return false;
    }
    private final function setDetails () : bool {

        $this->username = strtolower($this->data["username"]);
        $this->phone = $this->data["phone"];

        return true;

    }


    private final function  isValidLogin() : bool {
        $users_table_name = $this->users_table_name;
        $username = strtolower($this->username);
        $phone = $this->phone;
        $sql = "SELECT * FROM `{$users_table_name}` WHERE ((primary_phone = '{$phone}') OR (secondary_phone = '{$phone}')) AND username = '{$username}'";
        $result = $this->conn->prepare($sql);
        $result->execute();
        $num_rows = $result->rowCount();

        if($num_rows > 0) {
            return true;
        }


        return false;

    }
    private final function get_user_profile(): array
    {
        $users_table_name = $this->users_table_name;
        $username = strtolower($this->username);
        $phone = $this->phone;
        $sql = "SELECT * FROM `{$users_table_name}` WHERE (primary_phone = '{$phone}') OR (secondary_phone = '{$phone}') AND username = '{$username}'";
        $result = $this->conn->prepare($sql);
        $result->execute();
        $set_type_record = $result->setFetchMode(PDO::FETCH_ASSOC);
        $record = $result->fetchAll();
        return $record;
    }


    public final  function  Processor() {

        if($this->isReady()){

            $this->setDetails();

            if($this->isValidLogin()){
                $time = time();

                $thirty_days_from_now = (86400 * 30) + $time;
                $this->user_id = $this->get_user_profile()[0]["user_id"];
/*
                if ($this->remember_me != 1) {


                    setcookie("current_active_user" , "Deleted" , time() - 300 , "/");


                }
*
               */
                    setcookie("current_active_user" , $this->user_id , $thirty_days_from_now , "/");


                $profile = $this->get_user_profile()[0];
                $this->error = Array("success" => 1 , "error" => $this->successful_login , "profile" => $profile);
                $this->error = json_encode($this->error);
                $_SESSION["current_active_user"] = strtolower($this->user_id);
                return $this->error;










            }

            else {
                $this->error = Array("success" => 0 , "error" => $this->failed_login_error);
                $this->error = json_encode($this->error);
                return $this->error;


            }
        }
    }



}

$login = new Login();
echo $login->Processor();
?>