<?php
require_once $_SERVER["DOCUMENT_ROOT"]."/security/database.php";
class CheckVerificationCode extends  DatabaseConnection {
     public $user_profile;
     function __construct()
    {
        parent::__construct();

    }

    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    public function isValidCode () : bool  {
        if($this->record_exists_in_table($this->users_table_name , "email_verification_code" , $_GET["code"])){

        $this->user_profile = $this->fetch_data_from_table($this->users_table_name , "email_verification_code" , $_GET["code"]);
            if($this->update_record($this->users_table_name , "email_verified" ,"1", "email_verification_code" , $_GET["code"])){

           return true;
        }
        else {
            return false;
        }
}
else {
        return false;

        }
    }


}


$checkVerificationCode = new CheckVerificationCode();

if($checkVerificationCode->isValidCode()) {
$users_profile = $checkVerificationCode->user_profile[0];
    require_once ('req/other.php');
if(!class_exists("Configurations")) {
    require_once($document_root . '/security/config.php');


}

    $document_root = $_SERVER['DOCUMENT_ROOT'];

    $home_page_site_name = ucfirst($home_page_site_name);
    $site_features = "Electronics , Phones , Tablets , Home , Furniture and More";
    $page_title = "Email address (".$users_profile['email_address'].") verified successfully";
    $page_description = "Welcome to {$home_page_site_name}.com ";
    $page_keywords = "E-commerce,Phones,Tablets,Fashion,Clothes,Laptops,Computers,Beauty,Care,";
    $selected_state = "Rivers";
    $include_bootstrap = true;
    $include_custom_check_box = false;
    $include_bootstrap_js = false;
?>

<!DOCTYPE html>
<html lang="en-us" dir = "ltr" <?php echo $other_doctype_attribute; ?>>
<head>
    <?php require_once SITE_CONFIGURATIONS['HTML_FOLDER'].'meta.php'; ?>
    <link rel="stylesheet" href="<?php echo SITE_CONFIGURATIONS['CSS_FOLDER']?>bootstrap.min.css"/>
    <script type="text/javascript">
        $(document).ready(function () {

            $('#email-verified-alert').fadeIn('slow');
            setTimeout(function () {

                $('#email-verified-alert').fadeOut('slow');
                window.location.href = "/";
            } , 5000)
        });
    </script>
</head>
    <body>
    <div class="alert alert-info alerts fade in" id = "email-verified-alert" style="display:none;">
        <!--<strong id ="main-error-cause">Warning!</strong> Indicates a warning that might need attention. -->
        Your email address <strong><?php echo  $users_profile["email_address"]; ?></strong> has been verified sucessfully!

    </div>
    </body>
</html>


<?php } else {

    header('location: /invalidPage');
} ?>

