<?php
session_start();
if(!class_exists("Configurations")) {

    $document_root = $_SERVER['DOCUMENT_ROOT'];
    require_once($document_root . '/security/config.php');
    require_once($document_root . '/security/database.php');

}

$session_code = ($_SESSION["email_verification_code"]) ?? null;
$get_code  = ($_GET["code"]) ?? null;

$code = ($get_code) ?? $session_code;



if ($code == null) {

    header("Location: /404");
}

else {

    $code_length = mb_strlen($code);
    if ($code_length == $email_verification_code_length) {


    } else {

        class CheckEmailVerificationCode extends DatabaseConnection
        {


            function __construct()
            {

                parent::__construct();
            }

            function __destruct()
            {
                parent::__destruct(); // TODO: Change the autogenerated stub
            }

            public function get_code_profile(): array
            {
                global $code;
                $sql = "SELECT * FROM unverified_emails WHERE verification_code = '{$code}'";
                $result = $this->conn->prepare($sql);
                $result->execute();
                $set_type_record = $result->setFetchMode(PDO::FETCH_ASSOC);
                $record = $result->fetchAll();
                return $record;
            }


        }
        $validate_code = new CheckEmailVerificationCode();
        $profile =  $validate_code->get_code_profile();
        $_SESSION["email_verification_code"] = $code;
        if(empty($profile)) {

            header("location: /error");
        }

        else if ($session_code == null){
            $_SESSION["email_verification_code"] = $code;
            $_SESSION["existing_user_details"] = json_encode($profile[0]);
            header("Location: /completeRegistration");


        }

        else if ($session_code != null and $get_code != null and !empty($profile)){
            $_SESSION["existing_user_details"] = json_encode($profile[0]);
            header("Location: /completeRegistration");

        }

        $email_address = $profile[0]["email_address"];
    }

}




$min_number_length = $country_number_min_max[$selected_country][0];
$max_number_length = $country_number_min_max[$selected_country][1];
$phone_number_example = $country_number_min_max[$selected_country][2];
$country_international_code_format = $country_number_min_max[$selected_country][3];
require_once ('req/other.php');
$home_page_site_name = ucfirst($home_page_site_name);
$site_features = "Electronics , Phones , Tablets , Home , Furniture and More";
$page_title = "Final step...";
$page_description = "Complete your {$home_page_site_name}.com signup ";
$page_keywords = "user , profile , account , registration , signup , login , email";
$selected_state = "Rivers";
$include_bootstrap = true;
$include_custom_check_box = true;



?>
<!DOCTYPE html <?php echo $other_doctype_attribute; ?>>
<html lang="en-us" xmlns = "http://www.w3.org/1999/xhtml" dir="ltr">

<head>
    <link rel="stylesheet" href = "<?php  echo SITE_CONFIGURATIONS['CSS_FOLDER'].'home.css'; ?>" />

    <?php require_once SITE_CONFIGURATIONS['HTML_FOLDER'].'meta.php'; ?>
    <script type="text/javascript" src = "<?php  echo SITE_CONFIGURATIONS['JS_FOLDER'].'respond.min.js'; ?>" language = "JavaScript"></script>
    <script type="text/javascript" src = "<?php  echo SITE_CONFIGURATIONS['JS_FOLDER'].'html5shiv.js'; ?>" language = "JavaScript"></script>
    <script type="text/javascript" src = "<?php  echo SITE_CONFIGURATIONS['JS_FOLDER'].'completeRegistration.js'; ?>" language = "JavaScript"></script>
    <!-- Custom CSS -->
    <style>
        body {
            padding-top: 70px;
            /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
        }

        .othertop{margin-top:10px;}
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <![endif]-->


    <link rel="stylesheet" type="text/css" href="/styles/main_styles.css">
    <link rel="stylesheet" type="text/css" href="/styles/responsive.css">
    <link rel="stylesheet" href = "<?php  echo SITE_CONFIGURATIONS['CSS_FOLDER'].'account.css'; ?>" />

    <link rel="stylesheet" href = "<?php  echo SITE_CONFIGURATIONS['CSS_FOLDER'].'completeRegistration.css'; ?>" />
</head>

<body>

<div class="container">
    <div class="alert alert-success alerts" id = "success-alert">
        <!--<strong>Success!</strong> Indicates a successful or positive action. -->
    </div>


    <div class="alert alert-warning alerts" id = "failure-alert">
        <!--<strong id ="main-error-cause">Warning!</strong> Indicates a warning that might need attention. -->
    </div>
    <div class="row">
        <div class="col-md-10 ">
            <fieldset id="signup-form-fieldset">
                <form action="#" class="form-horizontal" name = "signup-form" id = "signup-form" method="post" enctype="application/x-www-form-urlencoded" autocomplete="on">


                    <!-- Form Name -->
                    <legend id = "signup-legend">Complete your registration</legend>

                    <!-- Text input-->







                    <!-- File Button -->

                    <!-- Text input-->
                    <!-- Text input-->

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label signup-labels" for="signup-username">Username</label>
                        <div class="col-md-4">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-user-circle" style="font-size: 20px;"></i>

                                </div>
                                <input id="signup-username" name="signup-username" type="text" placeholder="e.g vkPhones" class="form-control input-md" />

                            </div>
                            <span class = "signup-errors" id = "signup-username-error"></span>

                        </div>
                    </div>

                    <!-- Multiple Radios (inline) -->

                    <!-- Text input-->
                    <!-- <div class="form-group">
                      <label class="col-md-4 control-label" for="Temporary Address">Temporary Address</label>
                      <div class="col-md-4">

                      <div class="input-group">
                           <div class="input-group-addon">
                         <i class="fa fa-home" style="font-size:20px;"></i>

                           </div>
                     <input id="Temporary Address" name="Temporary Address" type="text" placeholder="Temporary Address" class="form-control input-md">
                          </div>


                      </div>
                    </div>
                     -->



                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label signup-labels" for="signup-primary-phone">Phone number </label>
                        <div class="col-md-4">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <img height="15px" src ="<?php echo SITE_CONFIGURATIONS['COUNTRY_FLAGS_FOLDER'].strtolower($selected_country).'.png'; ?>" />
                                    <span id="internation-code-format"><?php echo $country_international_code_format; ?></span>
                                </div>
                                <input id="signup-primary-phone" name="signup-primary-email" minlength="<?php echo $min_number_length;?>" maxlength="<?php echo $max_number_length; ?>" type="text" placeholder="<?php echo $phone_number_example?>" class="form-control input-md">

                            </div>
                            <span class = "signup-errors" id = "signup-primary-phone-error"></span>

                            <div class="input-group othertop">
                                <div class="input-group-addon">
                                    <i class="fa fa-phone"></i>
                                </div>
                                <input id="signup-secondary-phone" name="signup-secondary-phone" type="text" placeholder="Secondary Phone (if any)" class="form-control input-md">

                            </div>
                            <span class = "signup-errors" id = "signup-secondary-phone-error"></span>

                        </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label signup-labels" for="signup-email">Email Address</label>
                        <div class="col-md-4">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-envelope-o"></i>

                                </div>
                                <input id="signup-email" value="<?php echo $email_address; ?>" name="email" type="text" disabled="disabled" placeholder="Email Address" class="form-control input-md">

                            </div>
                            <span class = "signup-errors" id = "signup-email-error"></span>

                        </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                        <label class="col-md-4 control-label signup-labels" for="signup-password">Password</label>
                        <div class="col-md-4">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-key"></i>

                                </div>
                                <input type="password" placeholder="re-enter password" class="form-control input-md" id="signup-password" />

                            </div>
                            <a href = "#" id = "toggle-password-view" data-current-view = "password">Show password</a>
                            <span class = "signup-errors" id = "signup-password-error"></span>


                        </div>
                    </div>



                    <div class="form-group">
                        <label class="col-md-4 control-label" ></label>
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-success" id="signup-button"><span class="fa fa-thumbs-up signup-button-texts"></span><i class = "fa fa-spinner fa-spin" id = "signup-loading-icon"></i><i class="icon-hand-right signup-button-texts"></i><span id = "signup-button-text" class="signup-button-texts">&nbsp Submit</span></button>
                            <button type="reset"  class="btn btn-danger" value=""><span class="fa fa-window-close-o"></span> Clear</button>

                        </div>
                    </div>


                </form>
            </fieldset>
        </div>
        <div class="col-md-2 hidden-xs">
            <img src="<?php echo SITE_CONFIGURATIONS['IMG_FOLDER'].'avatar.jpg'; ?>" class="img-responsive img-thumbnail" />
        </div>


    </div>
</div>
<!-- jQuery Version 1.11.1 -->

<!-- Bootstrap Core JavaScript -->
<?php require_once SITE_CONFIGURATIONS['HTML_FOLDER'].'old-footer.php'; ?>
</body>

</html>
